# Generated by Django 6.1 on 2026-10-02 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('rol', models.CharField(choices=[('AUTOR', 'Autor'), ('LECTOR', 'Lector'), ('ADMIN', 'Administrador')], default='LECTOR', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('estado_actual', models.CharField(choices=[('BORRADOR', 'Borrador'), ('REVISION', 'En Revisión'), ('PUBLICADO', 'Publicado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=15)),
                ('visibilidad', models.CharField(choices=[('PUBLICA', 'Pública'), ('PRIVADA', 'Privada')], default='PUBLICA', max_length=10)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='publicaciones', to='noticia.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_interaccion', models.CharField(choices=[('LECTURA', 'Lectura'), ('GUARDADO', 'Guardado'), ('COMPARTIDO', 'Compartido')], max_length=15)),
                ('fecha_interaccion', models.DateTimeField(auto_now_add=True)),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticia.perfilusuario')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticia.publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=15)),
                ('estado_nuevo', models.CharField(max_length=15)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='noticia.publicacion')),
            ],
        ),
    ]
